export const GET_VIDEOS = "GET_VIDEOS";
export const STREAM_VIDEO = "STREAM_VIDEO";

export const CREATE_PRODUCER_ASYNC = "CREATE_PRODUCER_ASYNC";
export const CREATE_PRODUCER_SUCCESS = "CREATE_PRODUCER_SUCCESS";
export const CREATE_PRODUCER_FAILURE = "CREATE_PRODUCER_FAILURE";

export const CREATE_VIEWER_ASYNC = "CREATE_VIEWER_ASYNC";
export const CREATE_VIEWER_SUCCESS = "CREATE_VIEWER_SUCCESS";
export const CREATE_VIEWER_FAILURE = "CREATE_VIEWER_FAILURE";

export const UPLOAD_ASYNC = "UPLOAD_ASYNC";
export const VIDEO_READY_ASYNC = "VIDEO_READY_ASYNC";
export const VIDEO_SUCCESS = "UPLOAD_SUCCESS";
export const VIDEO_FAILURE = "UPLOAD_FAILURE";
export const VIDEO_READY = "VIDEO_READY";

export const VIEWER_VIDEOS_ASYNC = "VIEWER_VIDEOS_ASYNC";
export const VIEWER_VIDEOS_SUCCESS = "VIEWER_VIDEOS_SUCCESS";
export const VIEWER_VIDEOS_FAILURE = "VIEWER_VIDEOS_FAILURE";

export const GET_PAID_VIDEO_URL_ASYNC = "GET_PAID_VIDEO_URL_ASYNC";
export const GET_PAID_VIDEO_URL_SUCCESS = "GET_PAID_VIDEO_URL_SUCCESS";
export const GET_PAID_VIDEO_URL_FAILURE = "GET_PAID_VIDEO_URL_FAILURE";

export const PURCHASE_VIDEO_ASYNC = "PURCHASE_VIDEO_ASYNC";
export const PURCHASE_VIDEO_SUCCESS = "PURCHASE_VIDEO_SUCCESS";
export const PURCHASE_VIDEO_FAILURE = "PURCHASE_VIDEO_FAILURE";
