export const UPLOAD_VIDEO = "UPLOAD_VIDEO";
export const GET_VIDEOS = "GET_VIDEOS";
export const STREAM_VIDEO = "STREAM_VIDEO";

export const CREATE_PRODUCER_ASYNC = "CREATE_PRODUCER_ASYNC";
export const CREATE_PRODUCER_SUCCESS = "CREATE_PRODUCER_SUCCESS";
export const CREATE_PRODUCER_FAILURE = "CREATE_PRODUCER_FAILURE";

export const CREATE_VIEWER_ASYNC = "CREATE_VIEWER_ASYNC";
export const CREATE_VIEWER_SUCCESS = "CREATE_VIEWER_SUCCESS";
export const CREATE_VIEWER_FAILURE = "CREATE_VIEWER_FAILURE";
