export const GET_VIDEOS = "GET_VIDEOS";
export const STREAM_VIDEO = "STREAM_VIDEO";

export const CREATE_PRODUCER_ASYNC = "CREATE_PRODUCER_ASYNC";
export const CREATE_PRODUCER_SUCCESS = "CREATE_PRODUCER_SUCCESS";
export const CREATE_PRODUCER_FAILURE = "CREATE_PRODUCER_FAILURE";

export const CREATE_VIEWER_ASYNC = "CREATE_VIEWER_ASYNC";
export const CREATE_VIEWER_SUCCESS = "CREATE_VIEWER_SUCCESS";
export const CREATE_VIEWER_FAILURE = "CREATE_VIEWER_FAILURE";

export const UPLOAD_ASYNC = "UPLOAD_ASYNC";
export const VIDEO_READY_ASYNC = "VIDEO_READY_ASYNC";
export const VIDEO_SUCCESS = "UPLOAD_SUCCESS";
export const VIDEO_FAILURE = "UPLOAD_FAILURE";
export const VIDEO_READY = "VIDEO_READY";

export const VIEWER_VIDEOS_ASYNC = "VIEWER_VIDEOS_ASYNC";
export const VIEWER_VIDEOS_SUCCESS = "VIEWER_VIDEOS_SUCCESS";
export const VIEWER_VIDEOS_FAILURE = "VIEWER_VIDEOS_FAILURE";

export const VIEWER_LIVE_ASYNC = "VIEWER_LIVE_ASYNC";
export const VIEWER_LIVE_SUCCESS = "VIEWER_LIVE_SUCCESS";
export const VIEWER_LIVE_FAILURE = "VIEWER_LIVE_FAILURE";

export const PAID_VIEWER_VIDEOS_ASYNC = "PAID_VIEWER_VIDEOS_ASYNC";
export const PAID_VIEWER_VIDEOS_SUCCESS = "PAID_VIEWER_VIDEOS_SUCCESS";
export const PAID_VIEWER_VIDEOS_FAILURE = "PAID_VIEWER_VIDEOS_FAILURE";

export const GET_PAID_VIDEO_URL_ASYNC = "GET_PAID_VIDEO_URL_ASYNC";
export const GET_PAID_VIDEO_URL_SUCCESS = "GET_PAID_VIDEO_URL_SUCCESS";
export const GET_PAID_VIDEO_URL_FAILURE = "GET_PAID_VIDEO_URL_FAILURE";

export const PURCHASE_VIDEO_ASYNC = "PURCHASE_VIDEO_ASYNC";
export const PURCHASE_VIDEO_SUCCESS = "PURCHASE_VIDEO_SUCCESS";
export const PURCHASE_VIDEO_FAILURE = "PURCHASE_VIDEO_FAILURE";

export const USER_PAYMENT_INFO ="USER_PAYMENT_INFO"
export const ADD_PAYMENT_INFO_ASYNC = "ADD_PAYMENT_INFO_ASYNC";
export const ADD_PAYMENT_INFO_SUCCESS = "ADD_PAYMENT_INFO_SUCCESS";
export const ADD_PAYMENT_INFO_FAILURE = "ADD_PAYMENT_INFO_FAILURE";

export const GET_USER_PAYMENT_INFOS_ASYNC = "GET_USER_PAYMENT_INFOS_ASYNC";
export const GET_USER_PAYMENT_INFOS_SUCCESS = "GET_USER_PAYMENT_INFOS_SUCCESS";
export const GET_USER_PAYMENT_INFOS_FAILURE = "GET_USER_PAYMENT_INFOS_FAILURE";

export const SAVE_LATER_ASYNC = "SAVE_LATER_ASYNC";
export const SAVE_LATER_SUCCESS = "SAVE_LATER_SUCCESS";
export const SAVE_LATER_FAILURE = "SAVE_LATER_FAILURE";
export const SAVE_LATER_RESET = "SAVE_LATER_RESET";

export const GET_SAVED_VIDEOS_ASYNC = "GET_SAVED_VIDEOS_ASYNC";
export const GET_SAVED_VIDEOS_SUCCESS = "GET_SAVED_VIDEOS_SUCCESS";
export const GET_SAVED_VIDEOS_FAILURE = "GET_SAVED_VIDEOS_FAILURE";

export const ERROR_UNAUTHORIZED = "ERROR_UNAUTHORIZED";
